services:
  postgres:
    image: postgres:18
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" # Đổi cổng để không trùng với cổng 5432 của DB trên Windows
    volumes:
      - pgdata18:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # zookeeper: ĐÃ BỊ XÓA

  # rabbitmq: ĐÃ BỊ XÓA

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      # --- CẤU HÌNH KRAFT ---
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      # ID NÀY ĐƯỢC TẠO NGẪU NHIÊN, CHỈ CẦN DÙNG NÓ:
      CLUSTER_ID: 'dukK9ig5SCWCxZD_VoJs_g'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # --- CẤU HÌNH LISTENERS ---
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      # --- CÀI ĐẶT KHÁC ---
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
    ports:
      - "9092:9092"
      - "9093:9093"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_order_service:local
    # Xóa "rabbitmq" khỏi depends_on
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:${PG_HOST_PORT:-5432}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # --- CÁC BIẾN RABBITMQ ĐÃ BỊ XÓA ---
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_RABBITMQ_PORT: 5672
      # SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      # SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    ports:
      - "6868:6868"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6868/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  pgdata18: