server:
  port: 6868

spring:
  profiles:
    active: prod

  application:
    name: test-order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test-order-service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: test-result-full-ingest-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ---- ĐẢM BẢO ĐÃ XÓA value-deserializer và properties ở đây ----
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  events:
    enabled: false
    exchange-name: test-order-exchange

logging:
  level:
    root: INFO
    com.example.test_order_service: DEBUG

instrument:
  base-url: http://localhost:8081
  timeout-ms: 3000
  retry:
    max-attempts: 3
    backoff-ms: 500

wait:
  poll-interval-ms: 5000
  max-wait-ms: 600000